.catalog:
  name: "nginx"
  version: "latest"
  description: 
  questions:
    - variable: http_port
      description: "http port access"
      label: "Http Port"
      required: true
      default: "80"
      type: "int"
nginx:
